# Part I - Prosper Loan Data Exploration
## by Nkem 

 ## 1. Introduction

This data set contains 113,937 loans with 81 variables on each loan, including loan amount, borrower rate (or interest rate), current loan status, borrower income, and many others.

See data dictionary [here]('https://docs.google.com/spreadsheets/u/0/d/1gDyi_L4UvIrLTEC6Wri5nbaMmkGmLQBk-Yx3z0XDEtI/edit?usp=sharing')

In [33]:
# import all packages and set plots to be embedded inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

%matplotlib inline

In [ ]:
# load the dataset into a DataFrame
loan = pd.read_csv('prosperLoanData.csv')

In [37]:
# Make a copy of the dataset for reference
df = loan.copy()

In [13]:
print(" The data set is", format(loan.shape[0]), "rows and", loan.shape[1], "columns")

 The data set is 113937 rows and 81 columns

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 81 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   ListingKey                           113937 non-null  object
 1   ListingNumber                        113937 non-null  int64
 2   ListingCreationDate                  113937 non-null  object
 3   CreditGrade                          28953 non-null   object
 4   Term                                 113937 non-null  int64
 5   LoanStatus                           113937 non-null  object
 6   ClosedDate                           55089 non-null   object
 7   BorrowerAPR                          113912 non-null  float64
 8   BorrowerRate                         113937 non-null  float64
 9   LenderYield                          113937 non-null  float64
 10  EstimatedEffectiveYield              84853 non-null   float64
 11  EstimatedLoss                        84853 non-null   float64
 12  EstimatedReturn                      84853 non-null   float64
 13  ProsperRating (numeric)              84853 non-null   float64
 14  ProsperRating (Alpha)                84853 non-null   object
 15  ProsperScore                         84853 non-null   float64
 16  ListingCategory (numeric)            113937 non-null  int64
 17  BorrowerState                        108422 non-null  object
 18  Occupation                           110349 non-null  object
 19  EmploymentStatus                     111682 non-null  object
 20  EmploymentStatusDuration             106312 non-null  float64
 21  IsBorrowerHomeowner                  113937 non-null  bool
 22  CurrentlyInGroup                     113937 non-null  bool
 23  GroupKey                             13341 non-null   object
 24  DateCreditPulled                     113937 non-null  object
 25  CreditScoreRangeLower                113346 non-null  float64
 26  CreditScoreRangeUpper                113346 non-null  float64
 27  FirstRecordedCreditLine              113240 non-null  object
 28  CurrentCreditLines                   106333 non-null  float64
 29  OpenCreditLines                      106333 non-null  float64
 30  TotalCreditLinespast7years           113240 non-null  float64
 31  OpenRevolvingAccounts                113937 non-null  int64
 32  OpenRevolvingMonthlyPayment          113937 non-null  float64
 33  InquiriesLast6Months                 113240 non-null  float64
 34  TotalInquiries                       112778 non-null  float64
 35  CurrentDelinquencies                 113240 non-null  float64
 36  AmountDelinquent                     106315 non-null  float64
 37  DelinquenciesLast7Years              112947 non-null  float64
 38  PublicRecordsLast10Years             113240 non-null  float64
 39  PublicRecordsLast12Months            106333 non-null  float64
 40  RevolvingCreditBalance               106333 non-null  float64
 41  BankcardUtilization                  106333 non-null  float64
 42  AvailableBankcardCredit              106393 non-null  float64
 43  TotalTrades                          106393 non-null  float64
 44  TradesNeverDelinquent (percentage)   106393 non-null  float64
 45  TradesOpenedLast6Months              106393 non-null  float64
 46  DebtToIncomeRatio                    105383 non-null  float64
 47  IncomeRange                          113937 non-null  object
 48  IncomeVerifiable                     113937 non-null  bool
 49  StatedMonthlyIncome                  113937 non-null  float64
 50  LoanKey                              113937 non-null  object
 51  TotalProsperLoans                    22085 non-null   float64
 52  TotalProsperPaymentsBilled           22085 non-null   float64
 53  OnTimeProsperPayments                22085 non-null   float64
 54  ProsperPaymentsLessThanOneMonthLate  22085 non-null   float64
 55  ProsperPaymentsOneMonthPlusLate      22085 non-null   float64
 56  ProsperPrincipalBorrowed             22085 non-null   float64
 57  ProsperPrincipalOutstanding          22085 non-null   float64
 58  ScorexChangeAtTimeOfListing          18928 non-null   float64
 59  LoanCurrentDaysDelinquent            113937 non-null  int64
 60  LoanFirstDefaultedCycleNumber        16952 non-null   float64
 61  LoanMonthsSinceOrigination           113937 non-null  int64
 62  LoanNumber                           113937 non-null  int64
 63  LoanOriginalAmount                   113937 non-null  int64
 64  LoanOriginationDate                  113937 non-null  object
 65  LoanOriginationQuarter               113937 non-null  object
 66  MemberKey                            113937 non-null  object
 67  MonthlyLoanPayment                   113937 non-null  float64
 68  LP_CustomerPayments                  113937 non-null  float64
 69  LP_CustomerPrincipalPayments         113937 non-null  float64
 70  LP_InterestandFees                   113937 non-null  float64
 71  LP_ServiceFees                       113937 non-null  float64
 72  LP_CollectionFees                    113937 non-null  float64
 73  LP_GrossPrincipalLoss                113937 non-null  float64
 74  LP_NetPrincipalLoss                  113937 non-null  float64
 75  LP_NonPrincipalRecoverypayments      113937 non-null  float64
 76  PercentFunded                        113937 non-null  float64
 77  Recommendations                      113937 non-null  int64
 78  InvestmentFromFriendsCount           113937 non-null  int64
 79  InvestmentFromFriendsAmount          113937 non-null  float64
 80  Investors                            113937 non-null  int64
dtypes: bool(3), float64(50), int64(11), object(17)
memory usage: 68.1+ MB

In [16]:
# view data set in full using display
pd.options.display.max_columns = None
pd.options.display.max_rows = None


# show two entries
loan.head(2)

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,Occupation,EmploymentStatus,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentlyInGroup,GroupKey,DateCreditPulled,CreditScoreRangeLower,CreditScoreRangeUpper,FirstRecordedCreditLine,CurrentCreditLines,OpenCreditLines,TotalCreditLinespast7years,OpenRevolvingAccounts,OpenRevolvingMonthlyPayment,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,AmountDelinquent,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,RevolvingCreditBalance,BankcardUtilization,AvailableBankcardCredit,TotalTrades,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanKey,TotalProsperLoans,TotalProsperPaymentsBilled,OnTimeProsperPayments,ProsperPaymentsLessThanOneMonthLate,ProsperPaymentsOneMonthPlusLate,ProsperPrincipalBorrowed,ProsperPrincipalOutstanding,ScorexChangeAtTimeOfListing,LoanCurrentDaysDelinquent,LoanFirstDefaultedCycleNumber,LoanMonthsSinceOrigination,LoanNumber,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MemberKey,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
0,1021339766868145413AB3B,193129,2007-08-26 19:09:29.263000000,C,36,Completed,2009-08-14 00:00:00,0.16516,0.158,0.138,NaN,NaN,NaN,NaN,NaN,NaN,0,CO,Other,Self-employed,2.0,True,True,NaN,2007-08-26 18:41:46.780000000,640.0,659.0,2001-10-11 00:00:00,5.0,4.0,12.0,1,24.0,3.0,3.0,2.0,472.0,4.0,0.0,0.0,0.0,0.00,1500.0,11.0,0.81,0.0,0.17,"$25,000-49,999",True,3083.333333,E33A3400205839220442E84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,78,19141,9425,2007-09-12 00:00:00,Q3 2007,1F3E3376408759268057EDA,330.43,11396.14,9425.0,1971.14,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,0.0,258
1,10273602499503308B223C1,1209647,2014-02-27 08:28:07.900000000,NaN,36,Current,NaN,0.12016,0.092,0.082,0.0796,0.0249,0.0547,6.0,A,7.0,2,CO,Professional,Employed,44.0,False,False,NaN,2014-02-27 08:28:14,680.0,699.0,1996-03-18 00:00:00,14.0,14.0,29.0,13,389.0,3.0,5.0,0.0,0.0,0.0,1.0,0.0,3989.0,0.21,10266.0,29.0,1.00,2.0,0.18,"$50,000-74,999",True,6125.000000,9E3B37071505919926B1D82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,134815,10000,2014-03-03 00:00:00,Q1 2014,1D13370546739025387B2F4,318.93,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1

In [147]:
print( " The earliest date for this dataset is: ", df.ListingCreationDate.min())
print( " The latest date for this dataset is: ", df.ListingCreationDate.max())
print("Earliest Loan origination date: ", df.LoanOriginationDate.min())
print("Latest Loan origination date: ", df.LoanOriginationDate.max())
print(type(df.LoanOriginationDate[0]))

 The earliest date for this dataset is:  2005-11-09 20:44:28.847000000
 The latest date for this dataset is:  2014-03-10 12:20:53.760000000
Earliest Loan origination date:  2005-11-15 00:00:00
Latest Loan origination date:  2014-03-12 00:00:00
<class 'str'>

## 2. Preliminary Wrangling

I would be working with a subset of the dataset; Listings from August 2009.

In [162]:
after_july09 = df.query('ListingCreationDate >= "2009-08-01 00:00:00.000000000"' )
after_july09.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 84672 entries, 1 to 113936
Data columns (total 81 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ListingKey                           84672 non-null  object
 1   ListingNumber                        84672 non-null  int64
 2   ListingCreationDate                  84672 non-null  object
 3   CreditGrade                          0 non-null      object
 4   Term                                 84672 non-null  int64
 5   LoanStatus                           84672 non-null  object
 6   ClosedDate                           25824 non-null  object
 7   BorrowerAPR                          84672 non-null  float64
 8   BorrowerRate                         84672 non-null  float64
 9   LenderYield                          84672 non-null  float64
 10  EstimatedEffectiveYield              84672 non-null  float64
 11  EstimatedLoss                        84672 non-null  float64
 12  EstimatedReturn                      84672 non-null  float64
 13  ProsperRating (numeric)              84672 non-null  float64
 14  ProsperRating (Alpha)                84672 non-null  object
 15  ProsperScore                         84672 non-null  float64
 16  ListingCategory (numeric)            84672 non-null  int64
 17  BorrowerState                        84672 non-null  object
 18  Occupation                           83339 non-null  object
 19  EmploymentStatus                     84672 non-null  object
 20  EmploymentStatusDuration             84653 non-null  float64
 21  IsBorrowerHomeowner                  84672 non-null  bool
 22  CurrentlyInGroup                     84672 non-null  bool
 23  GroupKey                             1991 non-null   object
 24  DateCreditPulled                     84672 non-null  object
 25  CreditScoreRangeLower                84672 non-null  float64
 26  CreditScoreRangeUpper                84672 non-null  float64
 27  FirstRecordedCreditLine              84672 non-null  object
 28  CurrentCreditLines                   84672 non-null  float64
 29  OpenCreditLines                      84672 non-null  float64
 30  TotalCreditLinespast7years           84672 non-null  float64
 31  OpenRevolvingAccounts                84672 non-null  int64
 32  OpenRevolvingMonthlyPayment          84672 non-null  float64
 33  InquiriesLast6Months                 84672 non-null  float64
 34  TotalInquiries                       84672 non-null  float64
 35  CurrentDelinquencies                 84672 non-null  float64
 36  AmountDelinquent                     84672 non-null  float64
 37  DelinquenciesLast7Years              84672 non-null  float64
 38  PublicRecordsLast10Years             84672 non-null  float64
 39  PublicRecordsLast12Months            84672 non-null  float64
 40  RevolvingCreditBalance               84672 non-null  float64
 41  BankcardUtilization                  84672 non-null  float64
 42  AvailableBankcardCredit              84672 non-null  float64
 43  TotalTrades                          84672 non-null  float64
 44  TradesNeverDelinquent (percentage)   84672 non-null  float64
 45  TradesOpenedLast6Months              84672 non-null  float64
 46  DebtToIncomeRatio                    77391 non-null  float64
 47  IncomeRange                          84672 non-null  object
 48  IncomeVerifiable                     84672 non-null  bool
 49  StatedMonthlyIncome                  84672 non-null  float64
 50  LoanKey                              84672 non-null  object
 51  TotalProsperLoans                    19682 non-null  float64
 52  TotalProsperPaymentsBilled           19682 non-null  float64
 53  OnTimeProsperPayments                19682 non-null  float64
 54  ProsperPaymentsLessThanOneMonthLate  19682 non-null  float64
 55  ProsperPaymentsOneMonthPlusLate      19682 non-null  float64
 56  ProsperPrincipalBorrowed             19682 non-null  float64
 57  ProsperPrincipalOutstanding          19682 non-null  float64
 58  ScorexChangeAtTimeOfListing          16527 non-null  float64
 59  LoanCurrentDaysDelinquent            84672 non-null  int64
 60  LoanFirstDefaultedCycleNumber        6226 non-null   float64
 61  LoanMonthsSinceOrigination           84672 non-null  int64
 62  LoanNumber                           84672 non-null  int64
 63  LoanOriginalAmount                   84672 non-null  int64
 64  LoanOriginationDate                  84672 non-null  object
 65  LoanOriginationQuarter               84672 non-null  object
 66  MemberKey                            84672 non-null  object
 67  MonthlyLoanPayment                   84672 non-null  float64
 68  LP_CustomerPayments                  84672 non-null  float64
 69  LP_CustomerPrincipalPayments         84672 non-null  float64
 70  LP_InterestandFees                   84672 non-null  float64
 71  LP_ServiceFees                       84672 non-null  float64
 72  LP_CollectionFees                    84672 non-null  float64
 73  LP_GrossPrincipalLoss                84672 non-null  float64
 74  LP_NetPrincipalLoss                  84672 non-null  float64
 75  LP_NonPrincipalRecoverypayments      84672 non-null  float64
 76  PercentFunded                        84672 non-null  float64
 77  Recommendations                      84672 non-null  int64
 78  InvestmentFromFriendsCount           84672 non-null  int64
 79  InvestmentFromFriendsAmount          84672 non-null  float64
 80  Investors                            84672 non-null  int64
dtypes: bool(3), float64(50), int64(11), object(17)
memory usage: 51.3+ MB

In [185]:
after_july09.head(5)

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,Occupation,EmploymentStatus,EmploymentStatusDuration,IsBorrowerHomeowner,CurrentlyInGroup,GroupKey,DateCreditPulled,CreditScoreRangeLower,CreditScoreRangeUpper,FirstRecordedCreditLine,CurrentCreditLines,OpenCreditLines,TotalCreditLinespast7years,OpenRevolvingAccounts,OpenRevolvingMonthlyPayment,InquiriesLast6Months,TotalInquiries,CurrentDelinquencies,AmountDelinquent,DelinquenciesLast7Years,PublicRecordsLast10Years,PublicRecordsLast12Months,RevolvingCreditBalance,BankcardUtilization,AvailableBankcardCredit,TotalTrades,TradesNeverDelinquent (percentage),TradesOpenedLast6Months,DebtToIncomeRatio,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanKey,TotalProsperLoans,TotalProsperPaymentsBilled,OnTimeProsperPayments,ProsperPaymentsLessThanOneMonthLate,ProsperPaymentsOneMonthPlusLate,ProsperPrincipalBorrowed,ProsperPrincipalOutstanding,ScorexChangeAtTimeOfListing,LoanCurrentDaysDelinquent,LoanFirstDefaultedCycleNumber,LoanMonthsSinceOrigination,LoanNumber,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MemberKey,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
1,10273602499503308B223C1,1209647,2014-02-27 08:28:07.900000000,NaN,36,Current,NaN,0.12016,0.0920,0.0820,0.07960,0.0249,0.05470,6.0,A,7.0,2,CO,Professional,Employed,44.0,False,False,NaN,2014-02-27 08:28:14,680.0,699.0,1996-03-18 00:00:00,14.0,14.0,29.0,13,389.0,3.0,5.0,0.0,0.0,0.0,1.0,0.0,3989.0,0.21,10266.0,29.0,1.00,2.0,0.18,"$50,000-74,999",True,6125.000000,9E3B37071505919926B1D82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,134815,10000,2014-03-03 00:00:00,Q1 2014,1D13370546739025387B2F4,318.93,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
3,0EF5356002482715299901A,658116,2012-10-22 11:02:35.010000000,NaN,36,Current,NaN,0.12528,0.0974,0.0874,0.08490,0.0249,0.06000,6.0,A,9.0,16,GA,Skilled Labor,Employed,113.0,True,False,NaN,2012-10-22 11:02:32,800.0,819.0,1983-02-28 00:00:00,5.0,5.0,29.0,7,115.0,0.0,1.0,4.0,10056.0,14.0,0.0,0.0,1444.0,0.04,30754.0,26.0,0.76,0.0,0.15,"$25,000-49,999",True,2875.000000,A0393664465886295619C51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,16,77296,10000,2012-11-01 00:00:00,Q4 2012,9ADE356069835475068C6D2,321.45,5143.20,4091.09,1052.11,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
4,0F023589499656230C5E3E2,909464,2013-09-14 18:38:39.097000000,NaN,36,Current,NaN,0.24614,0.2085,0.1985,0.18316,0.0925,0.09066,3.0,D,4.0,2,MN,Executive,Employed,44.0,True,False,NaN,2013-09-14 18:38:44,680.0,699.0,2004-02-20 00:00:00,19.0,19.0,49.0,6,220.0,1.0,9.0,0.0,0.0,0.0,0.0,0.0,6193.0,0.81,695.0,39.0,0.95,2.0,0.26,"$100,000+",True,9583.333333,A180369302188889200689E,1.0,11.0,11.0,0.0,0.0,11000.0,9947.9,NaN,0,NaN,6,102670,15000,2013-09-20 00:00:00,Q3 2013,36CE356043264555721F06C,563.97,2819.85,1563.22,1256.63,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,0.0,20
5,0F05359734824199381F61D,1074836,2013-12-14 08:26:37.093000000,NaN,60,Current,NaN,0.15425,0.1314,0.1214,0.11567,0.0449,0.07077,5.0,B,10.0,1,NM,Professional,Employed,82.0,True,False,NaN,2013-12-14 08:26:40,740.0,759.0,1973-03-01 00:00:00,21.0,17.0,49.0,13,1410.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,62999.0,0.39,86509.0,47.0,1.00,0.0,0.36,"$100,000+",True,8333.333333,C3D63702273952547E79520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,3,123257,15000,2013-12-24 00:00:00,Q4 2013,874A3701157341738DE458F,342.37,679.34,351.89,327.45,-25.33,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
6,0F0A3576754255009D63151,750899,2013-04-12 09:52:56.147000000,NaN,36,Current,NaN,0.31032,0.2712,0.2612,0.23820,0.1275,0.11070,2.0,E,2.0,1,KS,Sales - Retail,Employed,172.0,False,False,NaN,2013-04-12 09:52:53,680.0,699.0,2000-09-29 00:00:00,10.0,7.0,20.0,6,214.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5812.0,0.72,1929.0,16.0,0.68,0.0,0.27,"$25,000-49,999",True,2083.333333,CE963680102927767790520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,11,88353,3000,2013-04-18 00:00:00,Q2 2013,AA4535764146102879D5959,122.67,1226.70,604.25,622.45,-22.95,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1

I will be making use of the numeric prosper rating from HR = 0, TO AA = 7

In [ ]:
# Convert LoanStatus, ProsperRating (Alpha), ProsperScore into ordered categorical types
ordinal_var_dict = {'ProsperRating (Alpha)': ['HR', 'E', 'D', 'C', 'B', 'A', 'AA'],
                    'ProsperScore': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
                    'IncomeRange' : [ 'Not employed', '$0', '$1-24,999', '$25,000-49,999', '$50,000-74,999','$75,000-99,999','$100,000+']}

In [159]:
after_july09.IncomeRange.value_counts()

$50,000-74,999    25561
$25,000-49,999    24119
$100,000+         15189
$75,000-99,999    14469
$1-24,999          4644
Not employed        647
$0                   43
Name: IncomeRange, dtype: int64

From this dataset, we see clearly

- store columns with null values as `incomplete`
- store columns with non null values as `complete`

In [348]:
# columns with null values
isnull = after_july09.isnull().sum()
incomplete = isnull.loc[ after_july09.shape[0] > isnull]
incomplete = incomplete[incomplete > 0]
incomplete.index

Index(['ClosedDate', 'Occupation', 'EmploymentStatusDuration', 'GroupKey',
       'DebtToIncomeRatio', 'TotalProsperLoans', 'TotalProsperPaymentsBilled',
       'OnTimeProsperPayments', 'ProsperPaymentsLessThanOneMonthLate',
       'ProsperPaymentsOneMonthPlusLate', 'ProsperPrincipalBorrowed',
       'ProsperPrincipalOutstanding', 'ScorexChangeAtTimeOfListing',
       'LoanFirstDefaultedCycleNumber'],
      dtype='object')

In [349]:
#generate a list of these columns
b =list(incomplete.index)

In [351]:
#get the not null collumns using the difference funcion
null_columns = b
  
notnull_columns = after_july09.columns.difference(null_columns)
notnull_columns

Index(['AmountDelinquent', 'AvailableBankcardCredit', 'BankcardUtilization',
       'BorrowerAPR', 'BorrowerRate', 'BorrowerState', 'CreditGrade',
       'CreditScoreRangeLower', 'CreditScoreRangeUpper', 'CurrentCreditLines',
       'CurrentDelinquencies', 'CurrentlyInGroup', 'DateCreditPulled',
       'DelinquenciesLast7Years', 'EmploymentStatus',
       'EstimatedEffectiveYield', 'EstimatedLoss', 'EstimatedReturn',
       'FirstRecordedCreditLine', 'IncomeRange', 'IncomeVerifiable',
       'InquiriesLast6Months', 'InvestmentFromFriendsAmount',
       'InvestmentFromFriendsCount', 'Investors', 'IsBorrowerHomeowner',
       'LP_CollectionFees', 'LP_CustomerPayments',
       'LP_CustomerPrincipalPayments', 'LP_GrossPrincipalLoss',
       'LP_InterestandFees', 'LP_NetPrincipalLoss',
       'LP_NonPrincipalRecoverypayments', 'LP_ServiceFees', 'LenderYield',
       'ListingCategory (numeric)', 'ListingCreationDate', 'ListingKey',
       'ListingNumber', 'LoanCurrentDaysDelinquent', 'LoanKey',
       'LoanMonthsSinceOrigination', 'LoanNumber', 'LoanOriginalAmount',
       'LoanOriginationDate', 'LoanOriginationQuarter', 'LoanStatus',
       'MemberKey', 'MonthlyLoanPayment', 'OpenCreditLines',
       'OpenRevolvingAccounts', 'OpenRevolvingMonthlyPayment', 'PercentFunded',
       'ProsperRating (Alpha)', 'ProsperRating (numeric)', 'ProsperScore',
       'PublicRecordsLast10Years', 'PublicRecordsLast12Months',
       'Recommendations', 'RevolvingCreditBalance', 'StatedMonthlyIncome',
       'Term', 'TotalCreditLinespast7years', 'TotalInquiries', 'TotalTrades',
       'TradesNeverDelinquent (percentage)', 'TradesOpenedLast6Months'],
      dtype='object')

In [164]:
# columns with not null rows
notnull = after_july09.notnull().sum()
complete = notnull.loc[notnull >= after_july09.shape[0]]
complete.index

Index(['ListingKey', 'ListingNumber', 'ListingCreationDate', 'Term',
       'LoanStatus', 'BorrowerAPR', 'BorrowerRate', 'LenderYield',
       'EstimatedEffectiveYield', 'EstimatedLoss', 'EstimatedReturn',
       'ProsperRating (numeric)', 'ProsperRating (Alpha)', 'ProsperScore',
       'ListingCategory (numeric)', 'BorrowerState', 'EmploymentStatus',
       'IsBorrowerHomeowner', 'CurrentlyInGroup', 'DateCreditPulled',
       'CreditScoreRangeLower', 'CreditScoreRangeUpper',
       'FirstRecordedCreditLine', 'CurrentCreditLines', 'OpenCreditLines',
       'TotalCreditLinespast7years', 'OpenRevolvingAccounts',
       'OpenRevolvingMonthlyPayment', 'InquiriesLast6Months', 'TotalInquiries',
       'CurrentDelinquencies', 'AmountDelinquent', 'DelinquenciesLast7Years',
       'PublicRecordsLast10Years', 'PublicRecordsLast12Months',
       'RevolvingCreditBalance', 'BankcardUtilization',
       'AvailableBankcardCredit', 'TotalTrades',
       'TradesNeverDelinquent (percentage)', 'TradesOpenedLast6Months',
       'IncomeRange', 'IncomeVerifiable', 'StatedMonthlyIncome', 'LoanKey',
       'LoanCurrentDaysDelinquent', 'LoanMonthsSinceOrigination', 'LoanNumber',
       'LoanOriginalAmount', 'LoanOriginationDate', 'LoanOriginationQuarter',
       'MemberKey', 'MonthlyLoanPayment', 'LP_CustomerPayments',
       'LP_CustomerPrincipalPayments', 'LP_InterestandFees', 'LP_ServiceFees',
       'LP_CollectionFees', 'LP_GrossPrincipalLoss', 'LP_NetPrincipalLoss',
       'LP_NonPrincipalRecoverypayments', 'PercentFunded', 'Recommendations',
       'InvestmentFromFriendsCount', 'InvestmentFromFriendsAmount',
       'Investors'],
      dtype='object')

Having seen the not nulll columns,

I will select my columns of interest from this list of columns and assign them to a DataFrame `Prosper`

For my analysis, I'll be using my sampled DataFrame `prosper`

In [327]:
#creating my Dataframe
prosper = after_july09[['ListingKey', 'Term',
       'BorrowerAPR', 'BorrowerRate', 'LenderYield',
        'ProsperRating (Alpha)', 'ProsperScore',
       'ListingCategory (numeric)', 'BorrowerState', 'EmploymentStatus',
       'IsBorrowerHomeowner', 'CurrentlyInGroup', 
       'IncomeRange', 'IncomeVerifiable', 'StatedMonthlyIncome', 'LoanMonthsSinceOrigination',
       'LoanOriginalAmount', 'LoanOriginationDate', 'LoanOriginationQuarter',
        'MonthlyLoanPayment', 'PercentFunded']]

## 3. visible and Programmatic assessment of the DataFrame

In [329]:

prosper.sample(3)

,ListingKey,Term,BorrowerAPR,BorrowerRate,LenderYield,ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,EmploymentStatus,IsBorrowerHomeowner,CurrentlyInGroup,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanMonthsSinceOrigination,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MonthlyLoanPayment,PercentFunded
54815,20BF3595081700422801B6C,60,0.21474,0.1905,0.1805,C,8.0,1,OH,Employed,True,False,"$50,000-74,999",True,4583.333333,3,8000,2013-12-04 00:00:00,Q4 2013,207.74,1.0
61727,1E5C3566464515684C1F8EB,36,0.12528,0.0974,0.0874,A,9.0,15,FL,Employed,True,False,"$75,000-99,999",True,7833.333333,14,15000,2013-01-15 00:00:00,Q1 2013,482.18,1.0
78670,B79535468976018414D9EEE,60,0.24702,0.2220,0.2120,C,5.0,6,MS,Employed,True,False,"$25,000-49,999",True,2487.333333,22,15000,2012-05-29 00:00:00,Q2 2012,415.99,1.0

In [330]:
prosper['ProsperRating (Alpha)'].value_counts()

C     18303
B     15566
A     14510
D     14249
E      9781
HR     6924
AA     5339
Name: ProsperRating (Alpha), dtype: int64

In [331]:
prosper.IncomeRange.value_counts()

$50,000-74,999    25561
$25,000-49,999    24119
$100,000+         15189
$75,000-99,999    14469
$1-24,999          4644
Not employed        647
$0                   43
Name: IncomeRange, dtype: int64

In [332]:
prosper.query('IncomeRange == "Not employed"').sample()

,ListingKey,Term,BorrowerAPR,BorrowerRate,LenderYield,ProsperRating (Alpha),ProsperScore,ListingCategory (numeric),BorrowerState,EmploymentStatus,IsBorrowerHomeowner,CurrentlyInGroup,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanMonthsSinceOrigination,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MonthlyLoanPayment,PercentFunded
22137,046D3536741370644A3DAA5,36,0.29394,0.2552,0.2452,D,5.0,14,FL,Not employed,False,False,Not employed,False,0.0,26,2500,2012-01-27 00:00:00,Q1 2012,100.09,1.0

## 4. Data Wrangling of the Prosper DataFrame.

In [333]:
# cleaning of the income range column
prosper['IncomeRange'].replace("Not employed", "$0", inplace=True)
prosper.IncomeRange.value_counts()

C:\Users\Prof. Dr. Nkem\AppData\Local\Temp\ipykernel_19164\899452949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prosper['IncomeRange'].replace("Not employed", "$0", inplace=True)

$50,000-74,999    25561
$25,000-49,999    24119
$100,000+         15189
$75,000-99,999    14469
$1-24,999          4644
$0                  690
Name: IncomeRange, dtype: int64

In [334]:
#Rename column names for readability
prosper = prosper.rename(columns={'ListingCategory (numeric)': 'ListingCategory',
                                                'ProsperRating (Alpha)': 'ProsperRating'})
prosper.sample()

,ListingKey,Term,BorrowerAPR,BorrowerRate,LenderYield,ProsperRating,ProsperScore,ListingCategory,BorrowerState,EmploymentStatus,IsBorrowerHomeowner,CurrentlyInGroup,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanMonthsSinceOrigination,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MonthlyLoanPayment,PercentFunded
64398,324A354239354240797ADA1,36,0.35797,0.3177,0.3077,HR,4.0,7,KS,Employed,False,False,"$1-24,999",True,1105.333333,23,2500,2012-04-09 00:00:00,Q2 2012,108.57,1.0

### Feature Engineering and column transformation to required data type.

> Cleaning the loan origination date

> Convert some columns to required data types

In [335]:
# transform date column and perform feature engineering
from datetime import datetime 
prosper['LoanOriginationDate'] = pd.to_datetime(prosper.LoanOriginationDate)
prosper['LoanOriginationYear'] = prosper['LoanOriginationDate'].dt.year
prosper['LoanOriginationMonth'] = prosper['LoanOriginationDate'].dt.month_name()
print(prosper.LoanOriginationYear.max())
print(prosper.LoanOriginationYear.min());
prosper.sample()

2014
2009

,ListingKey,Term,BorrowerAPR,BorrowerRate,LenderYield,ProsperRating,ProsperScore,ListingCategory,BorrowerState,EmploymentStatus,IsBorrowerHomeowner,CurrentlyInGroup,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanMonthsSinceOrigination,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MonthlyLoanPayment,PercentFunded,LoanOriginationYear,LoanOriginationMonth
111836,EE483592106800397AFBFC4,60,0.18965,0.166,0.156,C,9.0,1,PA,Employed,False,False,"$50,000-74,999",True,4333.333333,5,8000,2013-10-16,Q4 2013,197.1,1.0,2013,October

In [342]:
# Convert some columns to required data types
ordinal_var_dict = {'ProsperRating': ['HR','E','D','C', 'B', 'A', 'AA'],
                    'ProsperScore': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
                    'IncomeRange' : [ '$0', '$1-24,999', '$25,000-49,999', '$50,000-74,999','$75,000-99,999','$100,000+'],
                    'LoanOriginationMonth': ['January','Febuary', 'March','April','May','June','July','August','September','October','November','December'],
                   'LoanOriginationYear' : [2009, 2010, 2011, 2012, 2013, 2014],}
for var in ordinal_var_dict:
    ordered_var = pd.api.types.CategoricalDtype(ordered = True,
                                                categories = ordinal_var_dict[var])
    prosper[var] = prosper[var].astype(ordered_var)

prosper.ListingCategory = prosper.ListingCategory.astype('category')
prosper.Term = prosper.Term.astype(str)
prosper.IsBorrowerHomeowner = prosper.IsBorrowerHomeowner.astype('category')
prosper.EmploymentStatus = prosper.EmploymentStatus.astype('category')
prosper.LoanMonthsSinceOrigination = prosper.LoanMonthsSinceOrigination.astype(str)

In [343]:
prosper.describe()

,BorrowerAPR,BorrowerRate,LenderYield,StatedMonthlyIncome,LoanOriginalAmount,MonthlyLoanPayment,PercentFunded
count,84672.000000,84672.000000,84672.000000,8.467200e+04,84672.000000,84672.000000,84672.000000
mean,0.226738,0.196089,0.186084,5.933452e+03,9094.024341,292.256071,0.998094
std,0.079889,0.074605,0.074605,8.247730e+03,6288.611188,186.678157,0.020764
min,0.049350,0.040000,0.030000,0.000000e+00,1000.000000,0.000000,0.700000
25%,0.163610,0.135900,0.125900,3.441667e+03,4000.000000,157.580000,1.000000
50%,0.219450,0.187500,0.177500,5.000000e+03,7500.000000,252.225000,1.000000
75%,0.292540,0.257400,0.247400,7.083333e+03,13750.000000,389.030000,1.000000
max,0.423950,0.360000,0.340000,1.750003e+06,35000.000000,2251.510000,1.012500

In [344]:
# store the dataset 
prosper.to_csv('loanDataset.csv')

In [345]:
# make a copy for analysis.
df = prosper.copy()

In [346]:
#assess final dataset
print(df.shape)
print(df.dtypes);
df.sample()

(84672, 23)
ListingKey                            object
Term                                  object
BorrowerAPR                          float64
BorrowerRate                         float64
LenderYield                          float64
ProsperRating                       category
ProsperScore                        category
ListingCategory                     category
BorrowerState                         object
EmploymentStatus                    category
IsBorrowerHomeowner                 category
CurrentlyInGroup                        bool
IncomeRange                         category
IncomeVerifiable                        bool
StatedMonthlyIncome                  float64
LoanMonthsSinceOrigination            object
LoanOriginalAmount                     int64
LoanOriginationDate           datetime64[ns]
LoanOriginationQuarter                object
MonthlyLoanPayment                   float64
PercentFunded                        float64
LoanOriginationYear                 category
LoanOriginationMonth                category
dtype: object

,ListingKey,Term,BorrowerAPR,BorrowerRate,LenderYield,ProsperRating,ProsperScore,ListingCategory,BorrowerState,EmploymentStatus,IsBorrowerHomeowner,CurrentlyInGroup,IncomeRange,IncomeVerifiable,StatedMonthlyIncome,LoanMonthsSinceOrigination,LoanOriginalAmount,LoanOriginationDate,LoanOriginationQuarter,MonthlyLoanPayment,PercentFunded,LoanOriginationYear,LoanOriginationMonth
63722,C9773593621845283D39993,60,0.17174,0.1485,0.1385,B,8,1,WV,Employed,True,False,"$50,000-74,999",True,5625.0,4,10000,2013-11-07,Q4 2013,237.11,1.0,2013,November